name: Storybook
on:
  push:

env:
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

jobs:
  Chromatic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node
        uses: actions/setup-node@v6.1.0
        with:
          node-version-file: package.json
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install
      
      - shell: bash
        run: mkdir -p apps/web/public/_next-video

      - name: Build Storybook
        run: pnpm turbo run build:storybook

      - name: Chromatic @lapworth/xero
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN_XERO }}
          storybookBuildDir: packages/xero/storybook-static
          onlyChanged: true
          autoAcceptChanges: 'main'
          exitOnceUploaded: true

      - name: Chromatic lapworth.nz
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN_LAPWORTH }}
          storybookBuildDir: apps/web/storybook-static
          onlyChanged: true
          autoAcceptChanges: 'main'
          exitOnceUploaded: true
